# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ec50a3a236e536e50445be6b5c9e92be2e1060e37f9a8956e5220be42a84e13782f1e0382de1c8ba2885fbaecd678d419f085fe92fa88aa5c1f12198c8c516

test:
  secret_key_base: 25f5f7a56c2893104210d30b6b3ccfed4064bd1479e9524a651b34bbc9edea16a601a59356167914352620874d9b2e5cf667f80a7890b3befde54560b8e280cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
